import Foundation
import TinyGPTIO

/// `tinygpt to-coreml` — generates a Python conversion script that
/// turns a TinyGPT `.tinygpt` checkpoint into a CoreML `.mlpackage`.
///
/// Apple's CoreML format is a protobuf-backed bundle (.mlpackage)
/// produced via Python coremltools (no Swift-side writer exists as of
/// 2026). The honest deliverable from a Swift CLI is the bridge: a
/// Python script the user can run with their coremltools install.
///
/// The generated script:
///   1. parses the `.tinygpt` file format directly (we own the format)
///   2. rebuilds the transformer in PyTorch with the same shape
///   3. loads the weights from the `.tinygpt` manifest
///   4. traces + converts via `coremltools.convert`
///   5. writes a `.mlpackage` to disk
///
/// USAGE
///   tinygpt to-coreml <model.tinygpt> --out convert.py
///
/// Then on the host:
///   pip install coremltools numpy torch
///   python convert.py --input model.tinygpt --output model.mlpackage
///   open model.mlpackage   # opens in Xcode for profiling
///
/// Profile via Xcode's Instruments → Core ML template to see which ops
/// land on ANE / GPU / CPU. This is the prerequisite test for the ANE
/// experiment queued in PLAN.md §2.
enum ToCoreML {
    static func run(args: [String]) {
        var inputPath: String? = nil
        var outPath: String? = "convert.py"
        var i = 0
        while i < args.count {
            switch args[i] {
            case "--out":         outPath = args[i+1]; i += 2
            case "-h", "--help":  exitUsage(0)
            default:
                if args[i].hasPrefix("-") { fputs("unknown flag: \(args[i])\n", stderr); exitUsage() }
                inputPath = args[i]; i += 1
            }
        }
        guard let inputPath = inputPath else { fputs("missing <model.tinygpt>\n", stderr); exitUsage() }
        guard let outPath = outPath else { fputs("--out required\n", stderr); exitUsage() }

        // Read the .tinygpt header so the Python script can be tailored
        // to the model's specific arch (lets us emit the exact shape
        // constants rather than re-deriving them at runtime — clearer
        // when the user reads the script).
        let header: TinyGPTHeader
        do {
            let file = try TinyGPTFileReader.readMapped(URL(fileURLWithPath: inputPath))
            header = file.header
        } catch {
            fputs("could not read .tinygpt header: \(error)\n", stderr); exit(1)
        }
        let cfg = header.config

        let layers = cfg.layers ?? 12
        let dModel = cfg.dModel ?? 256
        let ctx = cfg.ctx ?? 256
        let heads = cfg.heads ?? 8
        let dMlp = cfg.dMlp ?? 1024
        let vocab = cfg.vocabSize ?? 256

        let script = """
        #!/usr/bin/env python3
        \"\"\"
        Auto-generated by `tinygpt to-coreml`. Converts a TinyGPT model
        into a CoreML .mlpackage via coremltools, loading weights from
        a safetensors file (produced via `tinygpt to-safetensors`).

        Model shape baked in from the .tinygpt header:
          layers      = \(layers)
          d_model     = \(dModel)
          n_heads     = \(heads)
          d_mlp       = \(dMlp)
          ctx         = \(ctx)
          vocab_size  = \(vocab)

        Run:
          # First convert .tinygpt → safetensors (Swift side):
          tinygpt to-safetensors \(inputPath) --out model.safetensors

          # Then run this script:
          pip install coremltools numpy torch safetensors
          python convert.py --input model.safetensors --output model.mlpackage

        Then profile in Xcode's Instruments → Core ML template to see
        which ops land on ANE / GPU / CPU. Prerequisite for the ANE
        experiment queued in PLAN.md §2.
        \"\"\"
        import argparse, math, sys
        from pathlib import Path

        try:
            import numpy as np
            import torch
            import torch.nn as nn
            from safetensors.torch import load_file
        except ImportError as e:
            sys.exit(f\"missing dep: {e}. pip install numpy torch coremltools safetensors\")

        # ===== Architecture (matches TinyGPTModel exactly) ===========
        N_LAYERS = \(layers)
        D_MODEL  = \(dModel)
        N_HEADS  = \(heads)
        D_MLP    = \(dMlp)
        CTX      = \(ctx)
        VOCAB    = \(vocab)
        HEAD_DIM = D_MODEL // N_HEADS

        class CausalSelfAttention(nn.Module):
            def __init__(self):
                super().__init__()
                self.q = nn.Linear(D_MODEL, D_MODEL)
                self.k = nn.Linear(D_MODEL, D_MODEL)
                self.v = nn.Linear(D_MODEL, D_MODEL)
                self.o = nn.Linear(D_MODEL, D_MODEL)
            def forward(self, x):
                B, T, C = x.shape
                q = self.q(x).view(B, T, N_HEADS, HEAD_DIM).transpose(1, 2)
                k = self.k(x).view(B, T, N_HEADS, HEAD_DIM).transpose(1, 2)
                v = self.v(x).view(B, T, N_HEADS, HEAD_DIM).transpose(1, 2)
                scores = (q @ k.transpose(-2, -1)) / math.sqrt(HEAD_DIM)
                mask = torch.triu(torch.ones(T, T) * -1e9, diagonal=1)
                scores = scores + mask
                attn = scores.softmax(dim=-1)
                out = (attn @ v).transpose(1, 2).contiguous().view(B, T, C)
                return self.o(out)

        class MLP(nn.Module):
            def __init__(self):
                super().__init__()
                self.fc_in = nn.Linear(D_MODEL, D_MLP)
                self.fc_out = nn.Linear(D_MLP, D_MODEL)
            def forward(self, x):
                return self.fc_out(torch.nn.functional.gelu(self.fc_in(x)))

        class Block(nn.Module):
            def __init__(self):
                super().__init__()
                self.ln1 = nn.LayerNorm(D_MODEL)
                self.attn = CausalSelfAttention()
                self.ln2 = nn.LayerNorm(D_MODEL)
                self.mlp = MLP()
            def forward(self, x):
                x = x + self.attn(self.ln1(x))
                x = x + self.mlp(self.ln2(x))
                return x

        class TinyGPT(nn.Module):
            def __init__(self):
                super().__init__()
                self.tok = nn.Embedding(VOCAB, D_MODEL)
                self.pos = nn.Embedding(CTX, D_MODEL)
                self.blocks = nn.ModuleList([Block() for _ in range(N_LAYERS)])
                self.ln_final = nn.LayerNorm(D_MODEL)
                self.head = nn.Linear(D_MODEL, VOCAB)
            def forward(self, idx):
                B, T = idx.shape
                pos = torch.arange(0, T, dtype=torch.long).unsqueeze(0)
                x = self.tok(idx) + self.pos(pos)
                for b in self.blocks: x = b(x)
                return self.head(self.ln_final(x))

        # ===== safetensors → PyTorch state dict =======================
        # The Swift-side `tinygpt to-safetensors` emits HF Llama tensor
        # names (model.embed_tokens.weight, model.layers.N.self_attn.q_proj.weight,
        # etc.). We map those back to the local TinyGPT module names
        # used by the class definitions above.
        NAME_MAP = {
            "model.embed_tokens.weight":     "tok.weight",
            "token_embedding.weight":        "tok.weight",     # --keep-names case
            "position_embedding.weight":     "pos.weight",     # TinyGPT's learned positional
            "model.norm.weight":             "ln_final.weight",
            "model.norm.bias":               "ln_final.bias",
            "ln_final.weight":               "ln_final.weight",
            "ln_final.bias":                 "ln_final.bias",
            "lm_head.weight":                "head.weight",
            "lm_head.bias":                  "head.bias",
        }
        for li in range(N_LAYERS):
            for src_pfx, dst_pfx in [
                (f"model.layers.{li}.input_layernorm",            f"blocks.{li}.ln1"),
                (f"model.layers.{li}.post_attention_layernorm",   f"blocks.{li}.ln2"),
                (f"model.layers.{li}.self_attn.q_proj",           f"blocks.{li}.attn.q"),
                (f"model.layers.{li}.self_attn.k_proj",           f"blocks.{li}.attn.k"),
                (f"model.layers.{li}.self_attn.v_proj",           f"blocks.{li}.attn.v"),
                (f"model.layers.{li}.self_attn.o_proj",           f"blocks.{li}.attn.o"),
                (f"model.layers.{li}.mlp.gate_proj",              f"blocks.{li}.mlp.fc_in"),
                (f"model.layers.{li}.mlp.down_proj",              f"blocks.{li}.mlp.fc_out"),
            ]:
                for suffix in (".weight", ".bias"):
                    NAME_MAP[src_pfx + suffix] = dst_pfx + suffix

        def load_into(model: nn.Module, safetensors_path: str) -> int:
            \"\"\"Load a safetensors file into the local TinyGPT model.
            Returns the number of tensors successfully mapped.\"\"\"
            sd_src = load_file(safetensors_path)
            sd_dst = model.state_dict()
            loaded = 0
            for src_name, tensor in sd_src.items():
                dst_name = NAME_MAP.get(src_name, src_name)
                if dst_name not in sd_dst:
                    print(f"  warn: no slot for '{src_name}' (mapped to '{dst_name}')")
                    continue
                # Cast to the destination's dtype (everything fp32 in
                # this script's TinyGPT class) and shape-check.
                if tuple(sd_dst[dst_name].shape) != tuple(tensor.shape):
                    print(f"  warn: shape mismatch on '{dst_name}': "
                          f"got {tuple(tensor.shape)}, want {tuple(sd_dst[dst_name].shape)}")
                    continue
                sd_dst[dst_name] = tensor.to(sd_dst[dst_name].dtype)
                loaded += 1
            model.load_state_dict(sd_dst, strict=False)
            return loaded

        def main():
            parser = argparse.ArgumentParser()
            parser.add_argument('--input', required=True, help='path to model.safetensors')
            parser.add_argument('--output', default='model.mlpackage')
            parser.add_argument('--compute-units', default='ALL',
                                  choices=['ALL', 'CPU_ONLY', 'CPU_AND_GPU', 'CPU_AND_NE'])
            args = parser.parse_args()

            try:
                import coremltools as ct
            except ImportError:
                sys.exit('coremltools not installed. pip install coremltools')

            print(f'loading {args.input}…')
            model = TinyGPT()
            loaded = load_into(model, args.input)
            print(f'loaded {loaded} tensors into the PyTorch model')
            model.eval()

            print('tracing…')
            example = torch.zeros(1, min(8, CTX), dtype=torch.long)
            traced = torch.jit.trace(model, example)

            print(f'converting to CoreML (compute_units={args.compute_units})…')
            mlmodel = ct.convert(
                traced,
                inputs=[ct.TensorType(name='tokens', shape=(1, ct.RangeDim(1, CTX)),
                                       dtype=np.int32)],
                outputs=[ct.TensorType(name='logits')],
                compute_units=getattr(ct.ComputeUnit, args.compute_units),
                minimum_deployment_target=ct.target.macOS14,
            )
            mlmodel.save(args.output)
            print(f'wrote {args.output}')
            print(f'profile via: xcrun mlcompute profile {args.output}  '
                  f'(or open in Xcode → Instruments → Core ML)')

        if __name__ == '__main__':
            main()
        """

        do {
            try script.write(toFile: outPath, atomically: true, encoding: .utf8)
            // Make the script executable.
            try? FileManager.default.setAttributes(
                [.posixPermissions: 0o755], ofItemAtPath: outPath)
            print("""

            TinyGPT — to-coreml conversion script generated
            ----------------------------------------------
            source:  \(inputPath)
            shape:   \(layers) layers × d_model=\(dModel) × heads=\(heads) × d_mlp=\(dMlp), vocab=\(vocab)
            wrote:   \(outPath) (\(script.utf8.count) bytes)

            Two-step conversion path:
              1) tinygpt to-safetensors \(inputPath) --out model.safetensors
              2) pip install coremltools numpy torch safetensors
                 python \(outPath) --input model.safetensors --output model.mlpackage

            Then profile with: open model.mlpackage  (Xcode → Instruments → Core ML)
            """)
        } catch {
            fputs("write failed: \(error)\n", stderr); exit(1)
        }
    }

    private static func exitUsage(_ code: Int32 = 2) -> Never {
        print("""
        usage: tinygpt to-coreml <model.tinygpt> [--out convert.py]

        Generates a Python script that converts a .tinygpt model to a
        CoreML .mlpackage via coremltools. Architecture, shape, and
        conversion driver are baked in from the .tinygpt header.
        Weights are loaded via safetensors — pipe through
        `tinygpt to-safetensors` first.

        Two-step:
          tinygpt to-safetensors model.tinygpt --out model.safetensors
          python convert.py --input model.safetensors --output model.mlpackage

        After running the script you get a .mlpackage that can be
        profiled in Xcode's Instruments → Core ML template to see
        which ops land on ANE / GPU / CPU. Prerequisite for the ANE
        experiment in PLAN.md §2.
        """)
        exit(code)
    }
}
